# Generated by Django 3.0.3 on 2021-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210109_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, max_length=258),
        ),
    ]
